version: '3.1'

services:
  db:
    build:
      context: ./postgres  # Diretório que contém o Dockerfile
      dockerfile: Dockerfile  # Nome do Dockerfile
    container_name: api-db
    restart: always
    tty: true
    ports:
      - '5435:5432'
    volumes:
      - '.docker/dbdata:/var/lib/postgresql/data'
    environment:
      - POSTGRES_PASSWORD=docker
      - POSTGRES_DB=projectdb
